name: Smart Data Lake Snapshot Build 2.12

on:
  push:
    branches: 
      - develop
      - develop-spark3
  pull_request:
    branches: 
      - develop
      - develop-spark3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven for Scala 2.12
      run: mvn -P scala-2.12 -B clean test --file pom.xml

    deploy:
      needs: build
      if: github.event.pull_request.merged == true

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Cache Maven
          uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-

        - name: Maven deploy to sonatype for Scala 2.12
            uses: samuelmeuli/action-maven-publish@v1
            with:
              gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
              gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
              nexus_username: ${{ secrets.SONATYPE_USERNAME }}
              nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
              maven_profiles: scala-2.12,release-sonatype
              maven_args: -B -f pom.xml
